-- Datos de prueba para experiencias
INSERT INTO experiences (id, title, description, price, location, duration, max_participants, photos, featured, category, what_is_included, what_is_needed, external_url, recurring_dates, created_at, updated_at) VALUES
(
  'exp-001',
  'Ruta de Tapas por el Casco Antiguo',
  'Descubre los mejores bares de tapas del casco antiguo con un guía local experto. Visitarás 5 bares tradicionales donde probarás las tapas más auténticas de la ciudad, acompañadas de vinos locales.',
  45.00,
  'Casco Antiguo, Málaga',
  180,
  8,
  ARRAY['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800'],
  true,
  'Gastronomía',
  '<ul><li>5 tapas diferentes</li><li>3 copas de vino local</li><li>Guía local experto</li><li>Historia de cada bar</li><li>Fotos del recorrido</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Zapatos para caminar</li><li>Ganas de probar nuevos sabores</li></ul>',
  'https://example.com/tapas-tour',
  '{"type": "weekly", "dates": [], "days": ["Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-002',
  'Paseo en Barco por la Costa',
  'Navega por las aguas cristalinas del Mediterráneo en un barco privado. Disfruta de vistas espectaculares de la costa, toma el sol en la cubierta y nada en calas vírgenes.',
  120.00,
  'Puerto de Málaga',
  240,
  6,
  ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
  true,
  'Aventura',
  '<ul><li>Barco privado</li><li>Capitán experimentado</li><li>Equipo de snorkel</li><li>Bebidas refrescantes</li><li>Almuerzo ligero</li></ul>',
  '<ul><li>Traje de baño</li><li>Toalla</li><li>Protector solar</li><li>Gafas de sol</li></ul>',
  'https://example.com/boat-tour',
  '{"type": "daily", "dates": [], "days": ["Lunes", "Miércoles", "Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-003',
  'Clase de Flamenco para Principiantes',
  'Aprende los pasos básicos del flamenco con una bailaora profesional. En esta clase de 2 horas descubrirás la pasión y el ritmo de este arte andaluz.',
  35.00,
  'Centro Cultural Flamenco, Málaga',
  120,
  12,
  ARRAY['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800'],
  false,
  'Cultura',
  '<ul><li>Clase de flamenco</li><li>Zapatos de flamenco</li><li>Vestido de flamenco</li><li>Video de la clase</li><li>Certificado de participación</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Zapatos con suela lisa</li><li>Mucha energía</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Martes", "Jueves"]}',
  NOW(),
  NOW()
),
(
  'exp-004',
  'Tour de Street Art por el Soho',
  'Explora el barrio del Soho y descubre las mejores obras de street art de la ciudad. Un artista local te guiará por las calles explicando el significado de cada mural.',
  25.00,
  'Barrio del Soho, Málaga',
  90,
  15,
  ARRAY['https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800'],
  false,
  'Arte',
  '<ul><li>Guía artista local</li><li>Explicación de cada obra</li><li>Fotos profesionales</li><li>Mapa del recorrido</li></ul>',
  '<ul><li>Zapatos cómodos</li><li>Cámara de fotos</li><li>Ganas de aprender</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Sábado", "Domingo"]}',
  NOW(),
  NOW()
),
(
  'exp-005',
  'Cata de Vinos en Bodega Local',
  'Visita una bodega familiar y aprende sobre el proceso de elaboración del vino. Degusta 6 vinos diferentes acompañados de quesos locales.',
  55.00,
  'Bodega Los Montes, Málaga',
  150,
  10,
  ARRAY['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'],
  true,
  'Gastronomía',
  '<ul><li>Tour por la bodega</li><li>Cata de 6 vinos</li><li>Quesos locales</li><li>Enólogo experto</li><li>Botella de vino de regalo</li></ul>',
  '<ul><li>Transporte a la bodega</li><li>Ropa casual</li><li>Interés por el vino</li></ul>',
  'https://example.com/wine-tasting',
  '{"type": "weekly", "dates": [], "days": ["Miércoles", "Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-006',
  'Sesión de Fotografía Profesional',
  'Captura los mejores momentos de tu viaje con una sesión de fotografía profesional en los lugares más emblemáticos de Málaga.',
  80.00,
  'Centro Histórico, Málaga',
  120,
  4,
  ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800', 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=800'],
  false,
  'Fotografía',
  '<ul><li>Fotógrafo profesional</li><li>3 ubicaciones diferentes</li><li>50 fotos editadas</li><li>Album digital</li><li>Fotos en alta resolución</li></ul>',
  '<ul><li>Ropa elegante</li><li>Accesorios personales</li><li>Sonrisa lista</li></ul>',
  NULL,
  '{"type": "daily", "dates": [], "days": ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]}',
  NOW(),
  NOW()
),
(
  'exp-007',
  'Clase de Cocina Mediterránea',
  'Aprende a cocinar los platos más típicos de la cocina mediterránea en una cocina profesional. Prepararás paella, gazpacho y otros platos tradicionales.',
  65.00,
  'Escuela de Cocina Mediterránea',
  180,
  8,
  ARRAY['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800'],
  true,
  'Gastronomía',
  '<ul><li>Chef profesional</li><li>Ingredientes frescos</li><li>Delantal y utensilios</li><li>Recetario digital</li><li>Degustación de lo preparado</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Ganas de cocinar</li><li>Apetito</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Martes", "Jueves", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-008',
  'Paseo en Segway por el Centro',
  'Explora el centro histórico de Málaga de una manera divertida y diferente. Recorre los monumentos más importantes sobre un Segway con guía incluido.',
  40.00,
  'Plaza de la Constitución, Málaga',
  90,
  6,
  ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
  false,
  'Aventura',
  '<ul><li>Segway eléctrico</li><li>Guía turístico</li><li>Casco de seguridad</li><li>Fotos del recorrido</li><li>Seguro incluido</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Zapatos cerrados</li><li>Edad mínima 12 años</li></ul>',
  'https://example.com/segway-tour',
  '{"type": "daily", "dates": [], "days": ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]}',
  NOW(),
  NOW()
),
(
  'exp-009',
  'Concierto de Flamenco Intimo',
  'Disfruta de un espectáculo de flamenco íntimo en un tablao tradicional. Música en vivo, baile y cante en un ambiente auténtico.',
  50.00,
  'Tablao Flamenco La Peña',
  120,
  20,
  ARRAY['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800'],
  true,
  'Cultura',
  '<ul><li>Espectáculo de flamenco</li><li>Bebida incluida</li><li>Tapas tradicionales</li><li>Músicos en vivo</li><li>Bailaores profesionales</li></ul>',
  '<ul><li>Ropa elegante casual</li><li>Reserva previa</li><li>Ganas de disfrutar</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-010',
  'Tour de Misterios y Leyendas',
  'Descubre los secretos más oscuros de Málaga en este tour nocturno. Historias de fantasmas, crímenes reales y leyendas urbanas.',
  30.00,
  'Plaza de la Merced, Málaga',
  120,
  15,
  ARRAY['https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800'],
  false,
  'Entretenimiento',
  '<ul><li>Guía especializado</li><li>Historias reales</li><li>Recorrido nocturno</li><li>Linterna incluida</li><li>Fotos del tour</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Zapatos para caminar</li><li>Valentía</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-011',
  'Clase de Surf para Principiantes',
  'Aprende a surfear en las playas de Málaga con instructores certificados. Incluye todo el equipo necesario y seguro.',
  70.00,
  'Playa de la Malagueta, Málaga',
  180,
  6,
  ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
  true,
  'Deportes',
  '<ul><li>Instructor certificado</li><li>Tabla de surf</li><li>Traje de neopreno</li><li>Seguro de accidentes</li><li>Fotos de la sesión</li></ul>',
  '<ul><li>Traje de baño</li><li>Toalla</li><li>Protector solar</li><li>Ganas de aprender</li></ul>',
  'https://example.com/surf-lesson',
  '{"type": "daily", "dates": [], "days": ["Lunes", "Miércoles", "Viernes", "Sábado", "Domingo"]}',
  NOW(),
  NOW()
),
(
  'exp-012',
  'Visita Guiada al Teatro Romano',
  'Explora las ruinas del teatro romano de Málaga con un arqueólogo experto. Descubre la historia de la ciudad en época romana.',
  20.00,
  'Teatro Romano, Málaga',
  90,
  12,
  ARRAY['https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800'],
  false,
  'Historia',
  '<ul><li>Arqueólogo guía</li><li>Entrada al teatro</li><li>Explicación detallada</li><li>Fotos permitidas</li><li>Folletos informativos</li></ul>',
  '<ul><li>Zapatos cómodos</li><li>Cámara de fotos</li><li>Interés por la historia</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Martes", "Jueves", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-013',
  'Paseo en Helicóptero por la Costa',
  'Disfruta de vistas espectaculares de Málaga y la costa desde el aire. Un vuelo de 15 minutos que te dejará sin aliento.',
  150.00,
  'Aeropuerto de Málaga',
  15,
  3,
  ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
  true,
  'Aventura',
  '<ul><li>Vuelo en helicóptero</li><li>Piloto experimentado</li><li>Vistas panorámicas</li><li>Video del vuelo</li><li>Certificado de vuelo</li></ul>',
  '<ul><li>Documentación válida</li><li>Ropa cómoda</li><li>Ganas de volar</li></ul>',
  'https://example.com/helicopter-tour',
  '{"type": "daily", "dates": [], "days": ["Lunes", "Miércoles", "Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-014',
  'Clase de Yoga en la Playa',
  'Practica yoga al amanecer en la playa con un instructor certificado. Una experiencia relajante y energizante.',
  25.00,
  'Playa de Pedregalejo, Málaga',
  90,
  10,
  ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
  false,
  'Bienestar',
  '<ul><li>Instructor certificado</li><li>Esterilla de yoga</li><li>Clase al amanecer</li><li>Meditación incluida</li><li>Té después de la clase</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Toalla</li><li>Agua</li><li>Ganas de relajarse</li></ul>',
  NULL,
  '{"type": "daily", "dates": [], "days": ["Lunes", "Miércoles", "Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-015',
  'Tour de Compras por el Centro',
  'Descubre las mejores tiendas y boutiques del centro de Málaga con una personal shopper experta.',
  40.00,
  'Centro Comercial Larios, Málaga',
  180,
  4,
  ARRAY['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800'],
  false,
  'Compras',
  '<ul><li>Personal shopper</li><li>Descuentos exclusivos</li><li>Consejos de estilo</li><li>Transporte entre tiendas</li><li>Almuerzo incluido</li></ul>',
  '<ul><li>Presupuesto para compras</li><li>Ropa cómoda</li><li>Ganas de comprar</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Martes", "Jueves", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-016',
  'Sesión de Masaje Relajante',
  'Disfruta de un masaje relajante de 60 minutos en un spa de lujo en el centro de Málaga.',
  80.00,
  'Spa Mediterráneo, Málaga',
  60,
  1,
  ARRAY['https://images.unsplash.com/photo-1544161512-6ad79e5fd09a?w=800', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800'],
  true,
  'Bienestar',
  '<ul><li>Masaje de 60 minutos</li><li>Aceites esenciales</li><li>Ambiente relajante</li><li>Bebida de bienvenida</li><li>Toallas y albornoz</li></ul>',
  '<ul><li>Llegar 15 min antes</li><li>Ropa cómoda</li><li>Ganas de relajarse</li></ul>',
  NULL,
  '{"type": "daily", "dates": [], "days": ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-017',
  'Clase de Guitarra Flamenca',
  'Aprende a tocar la guitarra flamenca con un guitarrista profesional. Clase individual o en grupo pequeño.',
  45.00,
  'Academia de Música Flamenca',
  90,
  4,
  ARRAY['https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
  false,
  'Música',
  '<ul><li>Guitarra flamenca</li><li>Profesor experto</li><li>Material didáctico</li><li>Grabación de la clase</li><li>Certificado de participación</li></ul>',
  '<ul><li>Ganas de aprender</li><li>Dedos listos</li><li>Paciencia</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Lunes", "Miércoles", "Viernes"]}',
  NOW(),
  NOW()
),
(
  'exp-018',
  'Tour de Arquitectura Moderna',
  'Descubre los edificios más modernos y vanguardistas de Málaga con un arquitecto local.',
  35.00,
  'Puerto de Málaga',
  120,
  8,
  ARRAY['https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800'],
  false,
  'Arquitectura',
  '<ul><li>Arquitecto guía</li><li>Explicación técnica</li><li>Fotos profesionales</li><li>Material informativo</li><li>Entrada a edificios</li></ul>',
  '<ul><li>Zapatos cómodos</li><li>Cámara de fotos</li><li>Interés por la arquitectura</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-019',
  'Cena en Rooftop con Vistas',
  'Disfruta de una cena gourmet en un rooftop exclusivo con vistas panorámicas de Málaga.',
  95.00,
  'Rooftop Mediterráneo, Málaga',
  180,
  6,
  ARRAY['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800'],
  true,
  'Gastronomía',
  '<ul><li>Cena de 4 platos</li><li>Vinos de la región</li><li>Vistas panorámicas</li><li>Chef personal</li><li>Fotos profesionales</li></ul>',
  '<ul><li>Ropa elegante</li><li>Reserva previa</li><li>Apetito</li></ul>',
  'https://example.com/rooftop-dinner',
  '{"type": "daily", "dates": [], "days": ["Viernes", "Sábado"]}',
  NOW(),
  NOW()
),
(
  'exp-020',
  'Tour Nocturno en Bicicleta',
  'Explora Málaga de noche en bicicleta eléctrica. Recorre los monumentos iluminados y disfruta de la ciudad sin tráfico.',
  30.00,
  'Plaza de la Merced, Málaga',
  120,
  8,
  ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
  false,
  'Aventura',
  '<ul><li>Bicicleta eléctrica</li><li>Casco de seguridad</li><li>Guía nocturno</li><li>Luces LED</li><li>Bebida de bienvenida</li></ul>',
  '<ul><li>Ropa cómoda</li><li>Zapatos cerrados</li><li>Ganas de pedalear</li></ul>',
  NULL,
  '{"type": "weekly", "dates": [], "days": ["Viernes", "Sábado"]}',
  NOW(),
  NOW()
); 